# Step 1: Build Angular app
FROM node:20.11.1 as build

WORKDIR /app

# Copy package.json and package-lock.json first to leverage Docker caching
COPY package*.json ./

# Install dependencies
RUN npm install --legacy-peer-deps

# Copy the rest of the application
COPY . .

# Install Angular CLI (optional, needed only for local development)
RUN npm install -g @angular/cli@19.0.1

# Build Angular for production
RUN npm run build --configuration=production

# Step 2: Serve with Nginx
FROM nginx:alpine

# Copy built Angular app to Nginx directory
COPY --from=build /app/dist/frontend /usr/share/nginx/html

# Copy custom Nginx configuration
COPY nginx.conf /etc/nginx/conf.d/default.conf


# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]

