version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb+srv://fouratmarouen4:anOQguy0LMLRubvr@dinaruisdb.u82qc.mongodb.net/dinaruisDB?retryWrites=true&w=majority&appName=DinaruisDB
    restart: unless-stopped
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    restart: unless-stopped

  mongo:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
   

volumes:
  mongo_data: