version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb+srv://fouratmarouen4:anOQguy0LMLRubvr@dinaruisdb.u82qc.mongodb.net/dinaruisDB?retryWrites=true&w=majority&appName=DinaruisDB

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
