# Use Node.js v20.11.1 as the base image
FROM node:20.11.1

# Set working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies with legacy-peer-deps
RUN npm install --legacy-peer-deps

# Copy the rest of the backend code
COPY . .

# Expose port (should match the one in your Express app)
EXPOSE 5000

# Start the server
CMD ["npm", "start"]
